<?php

namespace Tests\Unit\Http\Requests\OrderPicklist;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Requests\OrderPicklist\StoreRequest
 */
class StoreRequestTest extends TestCase
{
    /** @var \App\Http\Requests\OrderPicklist\StoreRequest */
    private $subject;

    protected function setUp(): void
    {
        parent::setUp();

        $this->subject = new \App\Http\Requests\OrderPicklist\StoreRequest();
    }

    /**
     * @test
     */
    public function authorize()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->authorize();

        $this->assertTrue($actual);
    }

    /**
     * @test
     */
    public function rules()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertValidationRules([
            'quantity_picked' => 'required|numeric',
            'order_product_ids' => 'required|array',
            'order_product_ids.*' => 'numeric',
        ], $actual);
    }

    // test cases...
}
