<?php

namespace Tests\Unit\Http\Requests\Picklist;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Requests\Picklist\StoreDeletedPickRequest
 */
class StoreDeletedPickRequestTest extends TestCase
{
    /** @var \App\Http\Requests\Picklist\StoreDeletedPickRequest */
    private $subject;

    protected function setUp(): void
    {
        parent::setUp();

        $this->subject = new \App\Http\Requests\Picklist\StoreDeletedPickRequest();
    }

    /**
     * @test
     */
    public function authorize()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->authorize();

        $this->assertTrue($actual);
    }

    /**
     * @test
     */
    public function rules()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertValidationRules([
            'quantity_picked' => 'numeric|required_without:quantity_skipped_picking',
            'quantity_skipped_picking' => 'numeric|required_without:quantity_picked',
            'order_product_ids' => 'required|array',
            'order_product_ids.*' => 'numeric|exists:order_products,id',
        ], $actual);
    }

    // test cases...
}
