<?php

namespace Tests\Routes\Api\Admin\User;

use App\Models\Invite;
use App\Models\Order;
use App\Models\Product;
use App\User;
use Laravel\Passport\Passport;
use Tests\TestCase;

class InvitesRoutesTest extends TestCase
{

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        User::query()->forceDelete();
        Product::query()->forceDelete();
        Order::query()->forceDelete();

        $user = factory(User::class)->create();
        Passport::actingAs($user);
        $user->assignRole('admin');

        factory(Order::class)->with('orderShipments', 2)->create();
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function testExample()
    {
        $invite = factory(Invite::class)->make();

        $response = $this->post('/api/admin/user/invites', $invite->toArray());

        $response->assertStatus(201);
    }
}
