<?php

namespace Tests\Feature\Http\Controllers\Api\Admin;

use App\Models\UserInvite;
use App\User;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Api\Admin\UserInviteController
 */
class UserInviteControllerTest extends TestCase
{
    /**
     * @test
     */
    public function accept_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $userInvite = factory(\App\Models\UserInvite::class)->create();

        $response = $this->get(route('accept', ['token' => $userInvite->token]));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function process_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $userInvite = factory(\App\Models\UserInvite::class)->create();

        $response = $this->post('invites/{token}', [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response()
    {
        $invite = factory(UserInvite::class)->make();
        $user = factory(User::class)->create()->assignRole('admin');

        $response = $this->actingAs($user, 'api')->postJson(route('invites.store'), [
            'email' => $invite->email
        ]);

        $response->assertSuccessful();

        $response->assertJsonStructure([
            'message'
        ]);
    }

    // test cases...
}
