<?php

namespace App\Modules\AutoStatusPicking\src;

use App\Events\HourlyEvent;
use App\Modules\AutoStatusPicking\src\Models\ModuleAutoStatusPickings;
use Exception;
use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;

/**
 * Class EventServiceProvider
 * @package App\Providers
 */
class EventServiceProvider extends ServiceProvider
{
    /**
     * @var \string[][]
     */
    protected $listen = [
        HourlyEvent::class => [
            Listeners\HourlyEvent\RefillStatusPickingListener::class,
        ],
    ];

    /**
     *
     */
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }

    /**
     * Register any events for your application.
     *
     * @return void
     */
    public function boot()
    {
        if ($this->isEnabled()) {
            parent::boot();
        }
    }

    /**
     * @return bool
     */
    public function isEnabled(): bool
    {
        try {
            return ModuleAutoStatusPickings::firstOrCreate([], [])->is_enabled ?? false;
        } catch (Exception $exception) {
            return false;
        }
    }
}
