<?php

namespace Tests\Feature\Verify;

use App\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class ResendTest extends TestCase
{
    use RefreshDatabase;

    protected string $uri = '';

    protected User $user;

    protected function setUp(): void
    {
        parent::setUp();
        $this->user = User::factory()->create();
    }

    /** @test */
    public function test_if_uri_set()
    {
        $this->markTestIncomplete('This test was generated by "php artisan app:generate-routes-tests" call');

        $this->assertNotEmpty($this->uri);
    }

    /** @test */
    public function test_guest_call()
    {
        $response = $this->get($this->uri);

        $response->assertRedirect('/login');
    }

    /** @test */
    public function test_user_call()
    {
        $this->markTestIncomplete('This test was generated by "php artisan app:generate-routes-tests" call');

        $this->actingAs($this->user, 'web');

        $response = $this->get($this->uri);

        $response->assertForbidden();
    }

    /** @test */
    public function test_admin_call()
    {
        $this->markTestIncomplete('This test was generated by "php artisan app:generate-routes-tests" call');

        $this->user->assignRole('admin');

        $this->actingAs($this->user, 'web');

        $response = $this->get($this->uri);

        $response->assertForbidden();
    }
}
